# Welcome to Marketing Report
author: Jack Lau <br>
last edit: 13/10/19 <br>
purpose: this report is use to show the advertising spending and pricing info in intopia

In [1]:
import pandas as pd
import os
from intopia_analysis import *

In [2]:
df_contact = pd.read_csv('Intopia - Contact List - Sheet1.csv')
df_price = get_live_price_data('phase2/period3/') #<---- ademend path between library 
df_ad = get_advertising_data('phase2/period7/') #<---- ademend path between library

# Team Tracking

In [3]:
team_tracker(df_contact, 17) #<-- admend the team you want information regarding

,Team Number,Team Member,Main Contact,Email,Facebook
73,17,"Berezovskaia, Katya",TRUE,NaN,https://www.facebook.com/katyaberez
74,17,"Lau, Jack",TRUE,tlau012@uottawa.ca,https://www.facebook.com/yuen.lau.927
75,17,"Duncan, Mackenzie",TRUE,mdunc101@uottawa.ca,https://www.facebook.com/mac.duncan.712
76,17,"Evan, Naylor",TRUE,enayl037@uottawa.ca,https://www.facebook.com/evan.naylor.79
77,17,"Kaminski, Patrick",NaN,NaN,https://www.facebook.com/patrick.kaminski.29

# Marketing Expense Tracking

## Central Canada Marketing Expese

In [4]:
df_ad[df_ad['region'] == 'cc'].sort_values(by=['type', 'Total'], ascending=False)

,Company,Print,TV,Social,Event,Sponsor,Retail,Web,Other,Total,type,region
1,13,600.00,600.00,600.00,600.00,600.00,600.00,600.00,600.00,4800.0,y,cc
3,17,300.00,250.00,100.00,250.00,500.00,100.00,250.00,0.00,1750.0,y,cc
0,9,210.00,210.00,495.00,83.00,83.00,166.00,413.00,0.00,1660.0,y,cc
4,25,0.00,250.00,250.00,0.00,250.00,0.00,0.00,0.00,750.0,y,cc
8,61,25.00,100.00,100.00,50.00,100.00,50.00,50.00,25.00,500.0,y,cc
6,40,0.00,100.00,50.00,50.00,50.00,50.00,0.00,0.00,300.0,y,cc
5,28,20.00,20.00,20.00,5.00,5.00,20.00,20.00,5.00,115.0,y,cc
7,45,0.00,0.00,30.00,0.00,0.00,30.00,0.00,0.00,60.0,y,cc
2,16,0.00,11.00,11.00,0.00,0.00,0.00,11.00,0.00,33.0,y,cc
1,9,135.00,135.00,328.00,55.00,55.00,110.00,274.00,0.00,1092.0,x,cc
2,17,100.00,100.00,0.00,100.00,100.00,100.00,500.00,0.00,1000.0,x,cc
5,34,10.00,50.00,200.00,75.00,75.00,100.00,25.00,10.00,545.0,x,cc
8,48,50.00,100.00,100.00,50.00,50.00,50.00,50.00,50.00,500.0,x,cc
10,61,25.00,100.00,100.00,50.00,100.00,50.00,50.00,25.00,500.0,x,cc
3,20,0.00,0.00,200.00,0.00,75.00,75.00,100.00,0.00,450.0,x,cc
7,40,0.00,200.00,100.00,50.00,50.00,0.00,0.00,0.00,400.0,x,cc
6,38,25.00,25.00,25.00,25.00,25.00,25.00,25.00,25.00,200.0,x,cc
4,28,10.00,10.00,10.00,0.00,0.00,10.00,10.00,0.00,50.0,x,cc
0,2,3.00,0.00,5.00,0.00,5.00,0.00,0.00,2.00,15.0,x,cc
9,52,0.00,5.00,10.00,0.00,0.00,0.00,0.00,0.00,15.0,x,cc

## Western Canada Marketing Expese

In [5]:
df_ad[df_ad['region'] == 'wc'].sort_values(by=['type','Total'], ascending=False)

,Company,Print,TV,Social,Event,Sponsor,Retail,Web,Other,Total,type,region
8,35,250.00,250.00,250.00,250.00,250.00,250.00,250.00,250.00,2000.0,y,wc
3,17,0.00,500.00,250.00,250.00,0.00,0.00,500.00,0.00,1500.0,y,wc
6,28,190.00,190.00,0.00,190.00,190.00,190.00,0.00,190.00,1140.0,y,wc
1,12,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,1000.0,y,wc
0,4,100.00,100.00,200.00,100.00,50.00,50.00,200.00,0.00,800.0,y,wc
4,25,0.00,0.00,250.00,0.00,0.00,0.00,250.00,0.00,500.0,y,wc
7,30,0.00,0.00,200.00,150.00,0.00,0.00,150.00,0.00,500.0,y,wc
13,61,25.00,100.00,100.00,50.00,100.00,25.00,100.00,0.00,500.0,y,wc
2,16,0.00,100.00,100.00,0.00,0.00,0.00,100.00,0.00,300.0,y,wc
5,27,0.00,0.00,0.00,100.00,0.00,100.00,100.00,0.00,300.0,y,wc
12,56,30.00,30.00,30.00,30.00,30.00,30.00,30.00,30.00,240.0,y,wc
9,42,10.00,10.00,25.00,10.00,10.00,25.00,10.00,0.00,100.0,y,wc
10,50,0.00,25.00,25.00,0.00,25.00,0.00,25.00,0.00,100.0,y,wc
11,51,0.00,0.00,20.00,0.00,0.00,0.00,0.00,0.00,20.0,y,wc
1,17,0.00,500.00,250.00,0.00,0.00,0.00,500.00,0.00,1250.0,x,wc
2,20,0.00,200.00,300.00,100.00,100.00,100.00,200.00,0.00,1000.0,x,wc
6,35,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,1000.0,x,wc
7,37,0.00,0.00,300.00,200.00,200.00,0.00,300.00,0.00,1000.0,x,wc
11,48,100.00,200.00,200.00,100.00,100.00,100.00,150.00,50.00,1000.0,x,wc
14,57,0.00,0.00,500.00,0.00,0.00,500.00,0.00,0.00,1000.0,x,wc
3,22,50.00,150.00,150.00,75.00,75.00,75.00,150.00,75.00,800.0,x,wc
4,28,120.00,120.00,0.00,120.00,120.00,120.00,0.00,120.00,720.0,x,wc
5,30,0.00,0.00,200.00,150.00,0.00,0.00,150.00,0.00,500.0,x,wc
15,61,25.00,100.00,100.00,50.00,100.00,25.00,100.00,0.00,500.0,x,wc
0,12,50.00,50.00,50.00,50.00,50.00,50.00,50.00,50.00,400.0,x,wc
9,41,0.00,0.00,60.00,0.00,0.00,0.00,60.00,0.00,120.0,x,wc
10,42,10.00,10.00,25.00,10.00,10.00,25.00,10.00,0.00,100.0,x,wc
12,50,0.00,25.00,25.00,0.00,25.00,0.00,25.00,0.00,100.0,x,wc
13,56,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,80.0,x,wc
8,39,0.00,5.00,5.00,0.00,0.00,0.00,6.00,0.00,16.0,x,wc

## Eastern Canada Marketing Expese

In [6]:
df_ad[df_ad['region'] == 'ec'].sort_values(by=['type','Total'], ascending=False)

,Company,Print,TV,Social,Event,Sponsor,Retail,Web,Other,Total,type,region
0,9,528.00,528.00,1000.00,180.00,180.00,205.00,898.00,0.00,3519.0,y,ec
1,12,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,1000.0,y,ec
2,17,0.00,500.00,0.00,0.00,0.00,0.00,500.00,0.00,1000.0,y,ec
3,27,0.00,0.00,0.00,0.00,0.00,0.00,50.00,0.00,50.0,y,ec
1,9,528.00,528.00,1077.00,180.00,180.00,200.00,898.00,0.00,3591.0,x,ec
5,21,0.00,250.00,500.00,100.00,0.00,0.00,400.00,0.00,1250.0,x,ec
4,20,0.00,0.00,400.00,200.00,0.00,60.00,300.00,0.00,960.0,x,ec
0,4,100.00,100.00,200.00,50.00,50.00,100.00,200.00,0.00,800.0,x,ec
3,17,0.00,500.00,0.00,0.00,0.00,0.00,250.00,0.00,750.0,x,ec
6,22,50.00,100.00,100.00,50.00,50.00,50.00,100.00,50.00,550.0,x,ec
2,12,50.00,50.00,50.00,50.00,50.00,50.00,50.00,50.00,400.0,x,ec
8,38,20.00,20.00,20.00,20.00,20.00,20.00,20.00,20.00,160.0,x,ec
7,27,0.00,0.00,50.00,0.00,50.00,0.00,0.00,0.00,100.0,x,ec
10,50,0.00,10.00,10.00,0.00,10.00,0.00,10.00,0.00,40.0,x,ec
9,43,0.00,0.00,10.00,0.00,0.00,0.00,10.00,0.00,20.0,x,ec

# Pricing Information

## Central Canada Live Price

In [ ]:
df_price[df_price['region'] == 'cc'].sort_values(by='Standard Price Cannabis', ascending=False)

## Western  Canada Live Price

In [ ]:
df_price[df_price['region'] == 'wc'].sort_values(by='Standard Price Cannabis', ascending=False)

## Eastern Canada Live Price

In [ ]:
df_price[df_price['region'] == 'ec'].sort_values(by='Standard Price Cannabis', ascending=False)